[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

upload_speed = 512000
monitor_speed = 115200

lib_ldf_mode = deep+
lib_deps = 
    adafruit/Adafruit IO Arduino @ ^4.3.7
lib_ignore = 
    WiFiNINA
    WiFiNINA_-_Adafruit_Fork
    WiFiNINA - Adafruit Fork